
export default interface IFilm {
    id                      : string,
    owner                   : string,
    name                    : string,
    old_name                : string,
    o_name                  : string,
    fname                   : string,
    description             : string,
    pic                     : string,
    cost                    : string,
    time                    : string,
    file                    : string,
    path                    : string,
    protocol                : string,
    rtsp_url                : string,
    censored                : string,
    hd                      : number,
    series                  : [],
    volume_correction       : string,
    category_id             : string,
    genre_id                : string,
    genre_id_1              : string,
    genre_id_2              : string,
    genre_id_3              : string,
    genre_id_4              : string,
    cat_genre_id_1          : string,
    cat_genre_id_2          : string,
    cat_genre_id_3          : string,
    cat_genre_id_4          : string,
    director                : string,
    actors                  : string,
    year                    : string,
    accessed                : string,
    status                  : string,
    disable_for_hd_devices  : string,
    added                   : string,
    count                   : string,
    count_first_0_5         : string,
    count_second_0_5        : string,
    vote_sound_good         : string,
    vote_sound_bad          : string,
    vote_video_good         : string,
    vote_video_bad          : string,
    rate                    : string,
    last_rate_update        : string,
    last_played             : string,
    for_sd_stb              : string,
    kinopoisk_id            : string,
    rating_kinopoisk        : string,
    rating_count_kinopoisk  : string,
    rating_imdb             : string,
    rating_count_imdb       : string,
    rating_last_update      : string,
    age                     : string,
    rating_mpaa             : string,
    high_quality            : string,
    comments                : string,
    low_quality             : number,
    country                 : string,
    screenshots             : string,
    sd                      : number,
    lock                    : number,
    fav                     : number,
    for_rent                : number,
    position                : number,
    screenshot_uri          : string,
    genres_str              : string,
    cmd                     : string,
    today                   : string,
    week_and_more           : string,
}

/*
{
  "js": {
    "total_items": "7609",
    "max_page_items": 14,
    "selected_item": 0,
    "cur_page": 0,
    "data": [
      {
        "id": "8278",
        "owner": "",
        "name": "Sex/Life: Season 01",
        "old_name": "",
        "o_name": "Sex/Life: Season 01",
        "fname": "",
        "description": "A woman's daring sexual past collides with her married-with-kids present when the bad-boy ex she can't stop fantasizing about crashes back into her life.",
        "pic": "",
        "cost": "0",
        "time": "47",
        "file": "",
        "path": "SexLife_Season_01_HD_2021",
        "protocol": "http",
        "rtsp_url": "",
        "censored": "0",
        "hd": 1,
        "series": [
          1,
          2,
          3,
          4,
          5,
          6,
          7,
          8
        ],
        "volume_correction": "0",
        "category_id": "8",
        "genre_id": "0",
        "genre_id_1": "0",
        "genre_id_2": "0",
        "genre_id_3": "0",
        "genre_id_4": "0",
        "cat_genre_id_1": "79",
        "cat_genre_id_2": "75",
        "cat_genre_id_3": "0",
        "cat_genre_id_4": "0",
        "director": "",
        "actors": "Sarah Shahi, Adam Demos, Mike Vogel, Phoenix Reich, Margaret Odette, Jonathan Sadowski, Li Jun Li, Meghan Heffern",
        "year": "2021",
        "accessed": "1",
        "status": "1",
        "disable_for_hd_devices": "0",
        "added": "2021-07-12 09:00:04",
        "count": "11",
        "count_first_0_5": "11",
        "count_second_0_5": "0",
        "vote_sound_good": "0",
        "vote_sound_bad": "0",
        "vote_video_good": "0",
        "vote_video_bad": "0",
        "rate": null,
        "last_rate_update": null,
        "last_played": "2021-07-12",
        "for_sd_stb": "0",
        "kinopoisk_id": "126280",
        "rating_kinopoisk": "7.2",
        "rating_count_kinopoisk": "163",
        "rating_imdb": "",
        "rating_count_imdb": "",
        "rating_last_update": "2021-07-05 10:49:40",
        "age": "",
        "rating_mpaa": "",
        "high_quality": "0",
        "comments": "",
        "low_quality": 0,
        "country": "United States of America",
        "screenshots": "8695",
        "sd": 0,
        "lock": 0,
        "fav": 0,
        "for_rent": 0,
        "position": 0,
        "screenshot_uri": "/stalker_portal/screenshots/87/8695.jpg",
        "genres_str": "Drama, Comedy",
        "cmd": "/media/8278.mpg",
        "today": "today"
      },
      {
        "id": "8270",
        "owner": "",
        "name": "The Superdeep",
        "old_name": "",
        "o_name": "The Superdeep",
        "fname": "",
        "description": "The film is based on real events when, in the 1970s, the deepest well in the world with a depth of more than 12 thousand meters was drilled in Murmansk Region for research purposes. During drilling, seismic sensors began to pick up strange sounds, an explosion occurred that led to mystical events.",
        "pic": "",
        "cost": "0",
        "time": "113",
        "file": "",
        "path": "The_Superdeep_HD_2020",
        "protocol": "http",
        "rtsp_url": "",
        "censored": "0",
        "hd": 1,
        "series": [],
        "volume_correction": "0",
        "category_id": "3",
        "genre_id": "0",
        "genre_id_1": "0",
        "genre_id_2": "0",
        "genre_id_3": "0",
        "genre_id_4": "0",
        "cat_genre_id_1": "31",
        "cat_genre_id_2": "93",
        "cat_genre_id_3": "20",
        "cat_genre_id_4": "0",
        "director": "Arseny Syukhin",
        "actors": "Artyom Tsukanov, Milena Radulović, Nikita Dyuvbanov, Kirill Kovbas, Vadim Demchog, Sergey Ivanuk, Nicholay Kovbas, Ilya Ilinykh",
        "year": "2020",
        "accessed": "1",
        "status": "1",
        "disable_for_hd_devices": "0",
        "added": "2021-07-05 09:00:10",
        "count": "34",
        "count_first_0_5": "34",
        "count_second_0_5": "0",
        "vote_sound_good": "0",
        "vote_sound_bad": "0",
        "vote_video_good": "0",
        "vote_video_bad": "0",
        "rate": null,
        "last_rate_update": null,
        "last_played": "2021-07-12",
        "for_sd_stb": "0",
        "kinopoisk_id": "579828",
        "rating_kinopoisk": "7",
        "rating_count_kinopoisk": "69",
        "rating_imdb": "",
        "rating_count_imdb": "",
        "rating_last_update": "2021-06-30 17:25:06",
        "age": "16+",
        "rating_mpaa": "",
        "high_quality": "0",
        "comments": "",
        "low_quality": 0,
        "country": "Russia",
        "screenshots": "8687",
        "sd": 0,
        "lock": 0,
        "fav": 0,
        "for_rent": 0,
        "screenshot_uri": "/stalker_portal/screenshots/87/8687.jpg",
        "genres_str": "Action, Thriller, Sci-fi",
        "cmd": "/media/8270.mpg",
        "week_and_more": "last week"
      }
    ]
  }
}

 */